version: '3.8'

services:
  web:
    build: .
    command: python3 -m app.main
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - .:/app
