{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flaskdocker.fullname" . }}-mysql
  labels:
    {{- include "flaskdocker.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.mysql.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
  {{- if .Values.mysql.persistence.storageClass }}
  storageClassName: {{ .Values.mysql.persistence.storageClass | quote }}
  {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flaskdocker.fullname" . }}-mysql
  labels:
    {{- include "flaskdocker.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.auth.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.auth.username | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.auth.password | quote }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.auth.rootPassword | quote }}
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ include "flaskdocker.fullname" . }}-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskdocker.fullname" . }}-mysql
  labels:
    {{- include "flaskdocker.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
